name: SPMU-marketing
favicon: null
layout_spectrum: 0.36565223755314946
typography_spectrum: 0.63751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9499174202792346
  lightness: 0.8190465730149299
  saturation: 0.692780441371724
  rhythmicContrast: 0.38892217306420207
purpose: []
